# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.hl7v2.fr.trans-cda-mss
canonical: https://interop.esante.gouv.fr/ig/hl7v2/trans-cda-mss # the last part of canonical and id must be the same
name: HL7v2_trans_CDA_MSS # Should be an acronym
title: Volet Transmission au LPS de documents CDA provenant d'un courriel MSSanté
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 1.1.1 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: "Accueil"
    volume1.md:
        title: "Volume 1 : Etude fonctionnelle"
    volume2.md:
        title: "Volume 2 : Détail des transactions" 
    lien-entete-cda-meta-xds.md:
        title: "Lien entre l'en-tête CDA et les métadonnées XDS"
    meta-dmp-mss.md:
        title: "Table MetaDMP/MSS"
    error-codes.md:
        title: "Codes erreurs de traitement du message HL7 MDM"    
    exemples.md:
        title: "Exemples de messages"
    struct-msg-mdn.md:
        title: "Structure du MDN (MSSanté)"
    glossaire.md:
        title: "Glossaire"
    doc-ref.md:
        title: "Documents de référence"
    testplan.md:
        title: "Test"
    change-log.md:
        title: "Historique des versions"
    download.md:
        title: "Téléchargements"    
        generation: markdown

menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: 
        "Cas d'usage": volume1.html#cas-dusage
        "Organisation métier": volume1.html#organisation-du-contexte-métier
        "Acteurs et transactions": volume1.html#acteurs-et-transactions
        "Définition des processus collaboratifs": volume1.html#définition-des-processus-collaboratifs
        "identification des flux": volume1.html#identification-des-flux
    Volume 2 – Détail des Transactions: 
        "Introduction": volume2.html#introduction
        "Périmètre de la transaction": volume2.html#périmetre-de-la-transaction
        "Rôle des acteurs pour cette transaction": volume2.html#rôle-des-acteurs-pour-cette-transaction
        "Choix des standards": volume2.html#choix-des-standards
        "Evènements déclenchants": volume2.html#evènements-déclenchants
        "Interactions entre les Acteurs": volume2.html#interactions-entre-les-acteurs
        "Profils de messages": volume2.html#profils-de-messages

    Volume 3 - Annexes:
        "Lien entre l'en-tête CDA et les métadonnées XDS": lien-entete-cda-meta-xds.html
        "Table MetaDMP/MSS": meta-dmp-mss.html
        "Codes erreurs de traitement du message HL7 MDM": error-codes.html
        "Exemples de messages": exemples.html
        "Structure du MDN (MSS)": struct-msg-mdn.html
        "Glossaire": glossaire.html
        "Documents de référence": doc-ref.html
    Test: testplan.html
    Historique des versions: change-log.html
    Téléchargements: download.html
 #   Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/